CREATE TABLE volier(
                       id int generated by default as identity  primary key,
                       volier_type varchar not null,
                       max_count_animals int not null,
                       count_animals int not null check ( count_animals <= volier.max_count_animals )
);



CREATE TABLE corm(
                     id int generated by default as identity primary key,
                     name varchar not null,
                     category varchar not null
);


CREATE TABLE animal(
                       id int generated by default as identity primary key,
                       type varchar not null,
                       category varchar not null,
                       name varchar not null,
                       weight int not null,
                       corm_id int references corm(id),
                       volier_id int references volier(id)
);


CREATE TABLE Employee(
                         id int generated by default as identity primary key,
                         role varchar not null,
                         name varchar not null,
                         surname varchar not null,
                         year_of_birthday int not null,
                         salary int not null
);


